name: Build changed projects

on:
  pull_request:
    branches: [main]

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-changed-projects.yml
    with:
      marker_file: README.md

  build:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJSON(needs.detect-changes.outputs.projects) }}
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ matrix.project }}


  build-summary:
    if: always()
    needs: [detect-changes, build]
    uses: ./.github/workflows/build-summary.yml
    with:
      detect_result: ${{ needs.detect-changes.result }}
      build_result: ${{ needs.build.result }}
